name: Markdown Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: '**.md'

jobs:
  mdchecks:
    name: Markdown Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS Tools
      uses: actions/setup-node@v1
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        list-files: shell
        filters: |
          markdown:
            - added|modified: '*.md'
    - name: Install dependencies
      if: ${{ steps.filter.outputs.markdown == 'true' }}
      run: |
        npm install -g markdownlint-cli
        npm install -g markdown-spellcheck
        npm install -g markdown-link-check
    - name: Lint check
      if: ${{ steps.filter.outputs.markdown == 'true' }}
      run: markdownlint ${{ steps.filter.outputs.markdown_files }}
    - name: Link check
      if: ${{ steps.filter.outputs.markdown == 'true' }}
      run: markdown-link-check ${{ steps.filter.outputs.markdown_files }}
    - name: Spell check
      if: ${{ steps.filter.outputs.markdown == 'true' }}
      run: mdspell -a -n -r -x --en-us ${{ steps.filter.outputs.markdown_files }}
