name: Gorfo

on: push

jobs:
  mdchecks:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS Tools
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli
        npm install -g markdown-spellcheck
        npm install -g markdown-link-validator
        npm install -g markdown-link-check
    - name: Lint
      run: |
        markdownlint ./README.md || exit 1
    - name: Link check
      run: |
        markdown-link-check ./README.md || exit 1
    - name: Spell check
      run: |
        mdspell -a -n -r -x --en-us ./README.md || exit 1
