name: Markdown Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: '**.md'

jobs:
  mdchecks:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS Tools
      uses: actions/setup-node@v1
    - name: Get File List
      run: |
        ping -c 5 www.google.com
        CMD=curl
        FOO=$(which $CMD)
        echo "BAR=$FOO" >> $GITHUB_ENV
    - name: Test BAR
      run: echo ${BAR}
    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli
        npm install -g markdown-spellcheck
        npm install -g markdown-link-check
    - name: Lint
      run: |
        markdownlint ${PR_MD_FILES} || exit 1
    - name: Link check
      run: |
        markdown-link-check ${PR_MD_FILES} || exit 1
    - name: Spell check
      run: |
        mdspell -a -n -r -x --en-us ${PR_MD_FILES} || exit 1
