name: Markdown Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: '**.md'

jobs:
  mdchecks:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS Tools
      uses: actions/setup-node@v1
    - name: Get File List
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        curl -v -s -H "Accept: application/vnd.github.v3+json" $URL
        JSON="$(curl -s -H \"Accept: application/vnd.github.v3+json\" $URL)"
        echo $JSON
        echo "BAR=\"$JSON\"" >> $GITHUB_ENV
    - name: Test BAR
      run: echo $BAR
    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli
        npm install -g markdown-spellcheck
        npm install -g markdown-link-check
    - name: Lint
      run: |
        markdownlint ${PR_MD_FILES} || exit 1
    - name: Link check
      run: |
        markdown-link-check ${PR_MD_FILES} || exit 1
    - name: Spell check
      run: |
        mdspell -a -n -r -x --en-us ${PR_MD_FILES} || exit 1
