name: Markdown Checks

on: push

jobs:
  mdchecks:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS Tools
      uses: actions/setup-node@v1
    - name: Get File List
      run: |
        URL="https://${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        PRFILES=$(curl -s -H "Accept: application/vnd.github.v3+json" $URL | grep '^ *"filename": ' | tr -d ' ' | cut -d':' -f2 | tr -d '",')
        echo ${PRFILES}
        echo "PR_MD_FILES=${PRFILES}" >> $GITHUB_ENV
    - name: Test PR_MD_FILES
      run: echo ${PR_MD_FILES}
    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli
        npm install -g markdown-spellcheck
        npm install -g markdown-link-check
    - name: Test
      run: echo $PR_MD_FILES
    - name: Lint
      run: |
        markdownlint ${PR_MD_FILES} || exit 1
    - name: Link check
      run: |
        markdown-link-check ${PR_MD_FILES} || exit 1
    - name: Spell check
      run: |
        mdspell -a -n -r -x --en-us ${PR_MD_FILES} || exit 1
