name: Gorfo

on: push

jobs:
  mdchecks:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS Tools
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        npm install -g markdownlint-cli
    - name: Lint with markdownlint-cli
      run: |
        markdownlint README.md || exit 1
